// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEEgJz1U1CXVSok5glmDkU2GVI3-39wQ',
    appId: '1:685041867247:web:237a78ed779d2303fabe1a',
    messagingSenderId: '685041867247',
    projectId: 'android-class-f9010',
    authDomain: 'android-class-f9010.firebaseapp.com',
    storageBucket: 'android-class-f9010.appspot.com',
    measurementId: 'G-0176TRWKQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sRFEKFY3YdQXjCnkci2FRf1Y3FQ7wXg',
    appId: '1:685041867247:android:723020db0be0fd4afabe1a',
    messagingSenderId: '685041867247',
    projectId: 'android-class-f9010',
    storageBucket: 'android-class-f9010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEAe3aN5Tkj6gA3y3am3p1vN7BWROOcY',
    appId: '1:685041867247:ios:bde21d922246a7a1fabe1a',
    messagingSenderId: '685041867247',
    projectId: 'android-class-f9010',
    storageBucket: 'android-class-f9010.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEAe3aN5Tkj6gA3y3am3p1vN7BWROOcY',
    appId: '1:685041867247:ios:bde21d922246a7a1fabe1a',
    messagingSenderId: '685041867247',
    projectId: 'android-class-f9010',
    storageBucket: 'android-class-f9010.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
